version: '3.8'
services:
  mysql:
    container_name: mysql80
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - mysql.env
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./my.cnf:/etc/my.cnf
      - ./sql/:/docker-entrypoint-initdb.d/
volumes:
  mysql-data:
